### ISSUE TITLE
About releasing some checkpoints

### ISSUE THREAD

**Issue by SongweiGe** [sihyun-yu/digan#1]
Great work and thanks for releasing the code! Do you have any following plans to release the trained models as well? Thanks!

**Comment by sihyun-yu** [comment]
Hi,

Thanks for your interest! 
We are planning to release the checkpoint soon as well. Since our code was refactored in some parts, we need the corresponding updates to pre-trained checkpoints (which were trained under uncleaned, previous implementation).

I will let you know when the checkpoint is released!

Sincerely,
Sihyun

**Comment by jihoontack** [comment]
Hi,

Thank you for your interest in our paper!

We have released checkpoints of the main table (see Table 1 in our paper).

You can download from the following [google drive link]( https://drive.google.com/drive/folders/1zrzyBMrqy7V_o4gGGLo_m2aErfshaFjz?usp=sharing)!

If you have any questions or issues, please let us know!

Best regards,
Jihoon
