### ISSUE TITLE
README file is a disaster.

### ISSUE THREAD

**Issue by nicolgo** [sihyun-yu/digan#13]
Following the README file, I failed to run the project. Here are some suggestions and questions:
1. I think the author should tell us the project only support Linux system at least.
2. I just want to train the model, but the guide is too simple. **Firstly**, what are the means of "<EXP_NAME>"? Can I think it is just a temp name, it is ok to pass any text? **Secondly**, how to change the training options? Can I run the project successfully without any changes? **Thirdly**, where to place the data directory? `data/UCF-101`?
3. it seems `launch.py` is just an encapsulation of `train.py`, since some default settings may not available for everyone, why not provide a set of `train.py` ?
4. I have looked through the project, code quality is good, but the README is really a disaster.

**Comment by sihyun-yu** [comment]
Hi,

1. Thank you for your suggestion. We did not add it since lots of deep learning implementation repositories assume the default system is built on Linux.
2. `EXP_NAME` specifies the temporal directory to save checkpoints and several logs. We omitted the detailed explanation since such a term is similarly (and widely) used in similar project repositories, e.g., [INR-GAN](https://github.com/universome/inr-gan). Anyway, I feel sorry if you are confused about this. Regarding the data directory,  you can manage it by modifying `configs/main.yml`. While we do not explicitly mention the data directory, but we mentioned, "You may change training options via modifying configs/main.yml" in the current README file. Considering the repositories is build a year ago and many people have already succeeded in reproducing the result, I think this is not a serious problem.
3. This project is built upon the popular [INR-GAN](https://github.com/universome/inr-gan) repository that uses `launch.py`and `train.py`. It copies the runner code to the experiment directory.

**Comment by nicolgo** [comment]
Hi sihyun,
Thanks for your time and explanation.
