### ISSUE TITLE
Zip dataset

### ISSUE THREAD

**Issue by torxxtorxx** [sihyun-yu/digan#8]
Hi,

thanks for your work! I want to use your repo with a .zip dataset, however I get following error:

File "/DIGAN/training/dataset.py", line 538, in __init__
    classes, class_to_idx = find_classes(path)
  File "/DIGAN/training/dataset.py", line 68, in find_classes
    classes = [d for d in os.listdir(dir) if os.path.isdir(os.path.join(dir, d))]
NotADirectoryError: [Errno 20] Not a directory: '/DIGAN/data/dataset.zip'

Also I wanted to ask if I can somehow combine your model with the FVD evaluation of StyleGAN-V. Can you maybe integrate their evaluation protocol into your pipeline on the fly during training? I am having problems doing that and I think their evaluation protocol uses a better FVD evaluation

**Comment by sihyun-yu** [comment]
Sorry for the confuse. We currently do not support .zip dataset -- but some snippets still remains in our implementation, as the original [codebase](https://github.com/NVlabs/stylegan2-ada) supported it.

For FVD evaluation proposed by StyleGAN-V, I certainly believe you can somehow combine our implementation and their evaluation, since they compared our method as a baseline. You may ask the StyleGAN-V authors how did they achieve this.
